# Generated by Django 3.1.5 on 2021-06-02 21:32

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210526_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tweets.models.upload_to),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
